### ISSUE TITLE
One possible error in Line 143 of the disentangle_cifar.py ?

### ISSUE THREAD

**Issue by datar001** [kai-wen-yang/CD-VAE#1]
![image](https://user-images.githubusercontent.com/62345916/146728334-5300518f-bfec-4610-acb0-7802fe1cbbfc.png)

There is not a variable named "entropy". Is it a typo ?

**Comment by datar001** [comment]
And, in Line 39 of the disentangle_cifar.py, we should get 5 values from vae model but expected 7 in Line 39. 
![image](https://user-images.githubusercontent.com/62345916/146738057-3853dc73-a286-499e-8c44-95327ff089e3.png)

**Comment by kai-wen-yang** [comment]
Yes, thanks for catching them and I have fixed them.
