### ISSUE TITLE
Can you share the VQ-VAE autoencoder model for the high resolution?

### ISSUE THREAD

**Issue by datar001** [kai-wen-yang/CD-VAE#2]
Hi, thanks for your sharing. This is a wonderful work. But this repo only contains the VAE model for the cifar-10 with the low resolution. If possible, can you share the VQ-VAE model for datasets with the high resolution?

And, the "mixup_data" operation in training stage seems to make model more robust.  Have you done some ablation experiments for evaluating this operation?

**Comment by kai-wen-yang** [comment]
Thanks for your interest. I have provided the VQ-VAE model for imagenet in CVAE_imagenet in vae.py https://github.com/kai-wen-yang/CD-VAE/blob/fa614cc930cf7c0ae2f19251678f247638ce197b/networks/vae.py#L230
I use it as:
```
model = CVAE_imagenet(d=64, k=128, num_classes=num_classes)
```
The training for imagenet is very similar to cifar.
I find mixup_data can lead to better disentanglement, especially the classification result for R(X). So I use it as the default setting and haven't done ablation experiments for it.

**Comment by GANG370** [comment]
The situation is still the same when the classification network is removed, but my Vqvae is completely based on your code, for binary classification, k=64, D =128 parameters should not be changed？
