### ISSUE TITLE
Are there gradient masking in your model?

### ISSUE THREAD

**Issue by zhiyang3344** [kai-wen-yang/CD-VAE#5]
Hi, the reported robust accuracy in Table6 of the paper is much higher than SOTA TRADES (~55.1% vs. ~77.05). To the best of our knowledge, there is no method that can improve robust accuracy by such a large margin, it is recommended to use Auto-Attack (https://github.com/fra31/auto-attack) to test the true robustness of your model.

**Comment by zhiyang3344** [comment]
> Hi, the reported robust accuracy in Table6 of the paper is much higher than SOTA TRADES (~55.1% vs. ~77.05). To the best of our knowledge, there is no method that can improve robust accuracy by such a large margin, it is recommended to use Auto-Attack (https://github.com/fra31/auto-attack) to test the true robustness of your model.

Sorry, the mentioned robust acc is your grey-box robust accuracy. The white-box robust accuracy of CD-VE under L_infy and L_2 in Table7 is much lower than that of AT and TRADES.

**Comment by kai-wen-yang** [comment]
Hi, we report grey-box robust accuracy in Table 6 and white-box robust accuracy (using Auto-attack) in Table 7. Although L_infty and L_2 is lower than AT and TRADES, our method can generalize well to unseen attacks.
