### ISSUE TITLE
about imagenet

### ISSUE THREAD

**Issue by mayfly227** [kai-wen-yang/CD-VAE#8]
is there any code for train CD-VAE-Imagenet?

**Comment by csjunjun** [comment]
Hi have you ever obtained the code about ImageNet? If so, could you please share it with me?

**Comment by mayfly227** [comment]
not yet，This method may have some issues

**Comment by mayfly227** [comment]
> Hi have you ever obtained the code about ImageNet? If so, could you please share it with me?


not yet，This method may have some issues

**Comment by csjunjun** [comment]
I think so. They do no give the parameter setting for training the cifar-10 neither. I test the target attack with target class 0 against resNet by using their pretrained model on their provided testset, and find that the avg/median. query i 1238/751, which are larger than 696/421 in Table 1 of the paper.

**Comment by kai-wen-yang** [comment]
> > Hi have you ever obtained the code about ImageNet? If so, could you please share it with me?
> 
> not yet，This method may have some issues

The implementation for imagenet is similar to cifar. The only difference is we use VQ-VAE for imagenet and I have provided the VQ-VAE code. Would you please implement it by yourself and concat me if you have any questions?

**Comment by kai-wen-yang** [comment]
> I think so. They do no give the parameter setting for training the cifar-10 neither. I test the target attack with target class 0 against resNet by using their pretrained model on their provided testset, and find that the avg/median. query i 1238/751, which are larger than 696/421 in Table 1 of the paper.

Could you please describe your experiments in detail? Table 1 of the paper does not contain the number 696/421.

**Comment by csjunjun** [comment]
![image](https://github.com/kai-wen-yang/CD-VAE/assets/8732743/afa3a3ec-98b8-4b97-a206-63cd95be1bfc)

**Comment by csjunjun** [comment]
Thank you for your reply. My 1238/751 result is obtained by attack your provided resnet_model.pth.tar on your provided 1000 images of test_cifar.npy. The attack parameters is the default value of your resnet.sh except for setting the target class as 0 as the same of Table 1. Of course, I filter images with the ground truth class 0.

**Comment by csjunjun** [comment]
I am so sorry that I confused another paper with yours. I'm very sorry for taking up your time >.<
